/* empty css                      */import{S as m}from"./assets/vendor-kodg3buk.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&l(o)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const c=[{img:"../img/users/john.png",alt:"john",feedback:"“ I’ve always struggled with meal prep. Now everything is planned, calorie-counted, and delivered right to my door. Huge time saver!”",username:"John D."},{img:"../img/users/ava.png",alt:"ava",feedback:"“The meal plans are super easy to follow and delivery is always on time. I’ve saved so much time during the week.”",username:"Ava A."},{img:"../img/users/james.png",alt:"james",feedback:"“I gained 6 kilograms of lean muscle in just two weeks. The fitness menu gives me exactly the calories and protein I need.”",username:"James D."},{img:"../img/users/olivia.png",alt:"olivia",feedback:"“Meals are fresh, tasty, and perfectly portioned. I don’t have to think about cooking after work — it’s all ready for me.”",username:"Olivia I."},{img:"../img/users/samantha.png",alt:"samantha",feedback:"“Lost 8 kilograms in three weeks without feeling hungry. The light plan makes dieting so much easier.”",username:"Samantha A."},{img:"../img/users/lusi.png",alt:"lusi",feedback:"“The maintenance plan keeps me in shape year-round. No more random diets — just balanced eating that works.”",username:"Lusi L."},{img:"../img/users/james-o.png",alt:"james-o",feedback:"“I don’t waste time cooking anymore. Everything comes ready and tastes like restaurant-quality meals.”",username:"James O."},{img:"../img/users/paul.png",alt:"paul",feedback:"“As a busy dad, the family menu is a lifesaver. Kids love it too, and I know they eat balanced meals every day.”",username:"Paul L."},{img:"../img/users/luke.png",alt:"luke",feedback:"“I finally stick to healthy eating because it’s simple. The variety each week keeps it exciting and never boring.”",username:"Luke D."},{img:"../img/users/katie.png",alt:"katie",feedback:"“I save around 8 hours every week thanks to this service. No shopping, no cooking — just healthy meals ready to enjoy.”",username:"Katie B."}];document.querySelector(".list").innerHTML=c.map(a=>`
  <li class="swiper-slide card">
    <div class="testimonial-image"><img src="${a.img}" alt="${a.alt}"/></div>
    <div class="testimonial-stars">★ ★ ★ ★ ★</div>
    <p class="person-feedback">${a.feedback}</p>
    <p class="name-of-person">${a.username}</p>
  </li>
`).join("");const t=new m(".mySwiper",{slidesPerView:3.4,spaceBetween:24,loop:!1}),n=document.querySelectorAll(".custom-pagination .dot");n.forEach(a=>{a.addEventListener("click",()=>{a.dataset.index==="first"&&t.slideTo(0),a.dataset.index==="last"&&t.slideTo(t.slides.length-1),a.dataset.index==="middle"&&t.slideTo(Math.floor(t.slides.length/2))})});const d=()=>{n.forEach(r=>r.classList.remove("active"));const a=t.maxTranslate(),i=t.translate;t.isBeginning?n[0].classList.add("active"):Math.abs(i-a)<1?n[2].classList.add("active"):n[1].classList.add("active")};t.on("slideChange",d);d();
//# sourceMappingURL=index.js.map
